version: '3.3'
services:
    api:
        image: tiangolo/uvicorn-gunicorn-fastapi:python3.7
        networks:
            - my_net
        volumes:
            - ./api:/app
        ports:
            - 8080:80
        restart: no

    database:
        image: postgres:latest
        networks:
            - my_net
        restart: no
        environment:  
            POSTGRES_PASSWORD: postgres  
            POSTGRES_DB: postgres
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - 5433:5432
        volumes:
            - ./database/conf/:/docker-entrypoint-initdb.d/
            - ./database/data/:/var/lib/postgresql/data
networks:
  my_net:
    driver: bridge
